name: CI pipeline on every commit

on: [push]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ics
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: talentboost
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Set up Java
        uses: actions/setup-java@v1.4.4
        with:
          java-version: '17'
      - name: Set perms
        run: cd backend && chmod +x ./gradlew
      - name: Build without tests
        run: cd backend && ./gradlew clean bootJar
      - name: Build and test
        run: cd backend && ./gradlew clean assemble test
      - name: Static code analysis
        run: cd backend && ./gradlew clean checkstyleMain
